#!/usr/bin/perl -wT
# -*- Mode: perl; tab-width: 4; indent-tabs-mode: nil; -*-
#
# multiform-01: Multiple forms demo 01
#
# Copyright (c) 2004 by Ian Hickson
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

use strict;
use utf8;
use CGI;
my $query = new CGI;
my $product = $query->param('product');
my $productcode = $query->param('productcode');

if (defined $productcode and length $productcode) {
    if ($productcode eq '1') {
        $product = 'The Test Product';
    }
} elsif (defined $product and length $product) {
    if ($product =~ m/Test/osi) {
        $productcode = '1';
    }
}

print <<EOF;
Content-Type: application/xml

<formdata xmlns="http://n.whatwg.org/formdata">
  <field name="productcode">$productcode</field>
  <field name="product">$product</field>
</formdata>
EOF
